feat

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,7 +38,14 @@ jobs:
             rm -rf /var/www/front
             mkdir /var/www/front
             cd /var/www/front'
-          rsync -avz -e "ssh" ./out/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front
-          rsync -avz -e "ssh" ./src/img ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front/
+          if ! rsync -avz -e "ssh" ./out/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front; then
+            echo "Rsync failed!"
+            exit 1
+          fi
+          if ! rsync -avz -e "ssh" ./src/img ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front/; then
+            echo "Rsync failed!"
+            exit 1
+          fi
+
       - name: Restart Nginx
         run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo service nginx restart'
